### ISSUE TITLE
Bug in rowSums,DelayedMatrix-method

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/DelayedArray#16]
Calling `rowSums()` on a large-ish _DelayedMatrix_ leads to a serialization/forking/memory issue on macOS and Linux

```R
library(DelayedArray)
x <- DelayedArray(matrix(1L, nrow = 10000000, ncol = 100))

# Errors
rowSums(x)
```

On macOS (16GB RAM) the error is:
```R
Error: vector memory exhausted (limit reached?)
```

On Linux (20GB RAM) the error is:

```R
Error in serialize(data, node$con, xdr = FALSE) : ignoring SIGPIPE signal
Error in serialize(data, node$con, xdr = FALSE) : ignoring SIGPIPE signal
Error: failed to stop ‘SOCKcluster’ cluster: error writing to connection
Error in serialize(data, node$con, xdr = FALSE) : ignoring SIGPIPE signal
# Then "Error in serialize(data, node$con, xdr = FALSE) : ignoring SIGPIPE signal" repeats indefinitely
```

I thought it might be a more general issue with `blockApply()` and its use of **BiocParallel**, but I haven't been able to trigger the problem in some brief testing. For example, using `colSums()` or `blockApply()`-ing `max()` over individual columns or rows of `x` worked fine.

**Comment by ttriche** [comment]
nb.  I see this problem even on Linux boxes with 384GB of RAM. 

It does not appear to be a small-memory issue per se.

**Comment by PeteHaitch** [comment]
@ttriche can you please try `DelayedMatrixStats::rowSums2()` and let me know if you still have the issue? It's implemented slightly differently

**Comment by ttriche** [comment]
I use rowSums2() in my code, but the trigger for this behavior seems to be
inside of the `dmrseq` package, and I haven't been able to track it down
yet.  Running some separate tests to try and figure it out now.


--t

**Comment by PeteHaitch** [comment]
@kdkorthauer Yes, it should be fixed now in **bsseq**. However, it's not clear to me if @ttriche's **dmrseq** example is triggering this issue from within **bsseq** or elsewhere in **dmrseq**. I'm happy to help debug this further

**Comment by kdkorthauer** [comment]
@PeteHaitch awesome, thanks! I'll investigate whether the issue persists within dmrseq, and if so whether a similar patch might work.

**Comment by mtmorgan** [comment]
DelayedArray does this

```
    bplapply(seq_len(nblock),
        function(b) {
            if (get_verbose_block_processing())
                message("Processing block ", b, "/", nblock, " ... ",
                        appendLF=FALSE)
            viewport <- grid[[b]]
            block <- extract_block(x, viewport)
            if (!is.array(block))
                block <- .as_array_or_matrix(block)
            attr(block, "from_grid") <- grid
            attr(block, "block_id") <- b
            block_ans <- FUN(block, ...)
            if (get_verbose_block_processing())
                message("OK")
            block_ans
        },
        BPREDO=BPREDO,
        BPPARAM=BPPARAM
    )
```
where `block <- extract_block(x, viewport)` is done on the worker. This means that `x` needs to be made available (serialized to, even in the case of `MulticoreParam()`) on the worker. A different implementation is to use `bpiterate()` and a generator function `ITER` to produce blocks on the manager. 
```
    ITER <- local({
        b <- 0L
        function() {
            b <<- b + 1L
            if (b > nblock)
                return(NULL)
            if (get_verbose_block_processing())
                message("Processing block ", b, "/", nblock, " ... ",
                        appendLF=FALSE)
            viewport <- grid[[b]]
            block <- extract_block(x, viewport)
            if (!is.array(block))
                block <- .as_array_or_matrix(block)
            attr(block, "from_grid") <- grid
            attr(block, "block_id") <- b
            block
        }
    })
            
    bpiterate(ITER, FUN, BPPARAM = BPPARAM)
```
This 'works' but is incredibly slow (use `set_verbose_block_processing(TRUE)` to convince yourself that it's chugging away) because the chunks are still serialized to each worker, and because the garbage collector is being called often; I'll explore a better solution for the common multicore data transfer problem in BiocParallel. Also I'm not sure where, if `x` were something like an HDF5Array, the object is actually realized in memory as a matrix; one would like to do that step on the worker.

I say 'works', but actually on my laptop (after setting `BiocParallel::register(BiocParallel::SerialParam())` for better speed) in the `rowSums,DelayedArray` method there is

```
    block_results <- blockApply(x, rowSums, na.rm=na.rm)

    ans <- rowSums(matrix(unlist(block_results, use.names=FALSE), nrow=nrow(x)))
```
and on the last line I end up with `Error: cannot allocate vector of size 7.5 Gb` -- the original object `x` is consuming 3.7G, `block_results` consumes 7.5G (these are doubles, rather than ints, which is a little surprising, I would have thought `rowSums()` would have returned ints if possible @lawremi), `unlist(block_results, use.names=FALSE)` is another 7.5G, and the `matrix(...)` is another 7.5G so 3.7G + 3 * 7.5G. At this point the `unlist()` result is available for garbage collection (is it?), but then `ans` takes its place using another 7.5G! If this has been written as

```
    result <- blockApply(x, rowSums, na.rm=na.rm)
    result <- unlist(result, use.names = FALSE)
    result <- matrix(result, nrow = nrow(x))
    result <- rowSums(result)
```
there would only ever need to be 3.7G + 2 x 7.5G in memory. 

Hmm, but now I'm confused! `unlist(blockApply())` is `as.vector(x)` (!), which we reshape into a matrix equal to x (except with numeric rather than integer type) and then we calculate rowSums locally! I guess DelayedArray has chosen to block into chunks where each chunk has a single row...

**Comment by hpages** [comment]
`unlist(blockApply())` is `as.vector(x)` because `blocApply()` is still using the old default block grid where the blocks go "along the columns". This is not optimal in most cases and needs to change. Will do ASAP.

**Comment by ttriche** [comment]
> library(DelayedArray)
Loading required package: stats4
Loading required package: matrixStats
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colMeans,
    colnames, colSums, dirname, do.call, duplicated, eval, evalq,
    Filter, Find, get, grep, grepl, intersect, is.unsorted, lapply,
    lengths, Map, mapply, match, mget, order, paste, pmax, pmax.int,
    pmin, pmin.int, Position, rank, rbind, Reduce, rowMeans, rownames,
    rowSums, sapply, setdiff, sort, table, tapply, union, unique,
    unsplit, which, which.max, which.min

Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: BiocParallel

Attaching package: ‘DelayedArray’

The following objects are masked from ‘package:matrixStats’:

    colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges

The following objects are masked from ‘package:base’:

    aperm, apply

> x <- DelayedArray(matrix(1L, nrow = 10000000, ncol = 100))
>
> # using matrixStats
> foo <- matrixStats:::rowSums(x)
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) :
  object 'rowSums' not found
> # using DelayedMatrixStats
> bar <- DelayedMatrixStats:::rowSums2(x)
# no error


--t

**Comment by ttriche** [comment]
also:

> foo <- matrixStats:::rowSums2(x)
Error in matrixStats:::rowSums2(x) :
  Argument 'x' must be a matrix or a vector.


--t

**Comment by PeteHaitch** [comment]
@ttriche @kdkorthauer 
The example needs to be:

```R
library(DelayedArray)
x <- DelayedArray(matrix(1L, nrow = 10000000, ncol = 100))
# Using DelayedArray
DelayedArray::rowSums(x)
# Using DelayedMatrixStats
DelayedMatrixStats::rowSums2(x)
```

**Comment by ttriche** [comment]
that one about crashed my machine in DelayedArray::rowSums(x)

--t

**Comment by ttriche** [comment]
started with R --vanilla:

> x <- DelayedArray(matrix(1L, nrow = 10000000, ncol = 100))
> # Using DelayedArray
> DelayedArray::rowSums(x)
# wait about 20 minutes
^C
^C
>
> ^D # to quit
Error: failed to stop 'SOCKcluster' cluster: invalid connection
Error while shutting down parallel: unable to terminate some child processes


So yeah I think I see where the problem is...



--t

**Comment by hpages** [comment]
I hope we can close this.

There have been many important changes and improvements to the block processing mechanism in DelayedArray over the past 18 months (and more are to come). With the latest version of DelayedArray (0.11.8), Pete's original code works on my Linux laptop (Ubuntu 16.04, with 16 Gb of RAM) and is fast. Only thing is that now it displays some strange error messages that seem to be stemming from BiocParallel:
```
library(DelayedArray)
x <- DelayedArray(matrix(1L, nrow=1e7, ncol=100))
rs1 <- DelayedArray::rowSums(x)
# Error in mcexit(0L) : ignoring SIGPIPE signal
# Error in mcexit(0L) : ignoring SIGPIPE signal
# Error in mcexit(0L) : ignoring SIGPIPE signal
# Error in mcexit(0L) : ignoring SIGPIPE signal
# Error in mcexit(0L) : ignoring SIGPIPE signal
# Error in mcexit(0L) : ignoring SIGPIPE signal
```
Not sure what's going on exactly but they seem harmless. Besides I only seem to get them on my laptop and I get them with things as simple as:
```
res <- bplapply(1:25000, identity)
# Error in mcexit(0L) : ignoring SIGPIPE signal
# Error in mcexit(0L) : ignoring SIGPIPE signal
```
which suggests that they don't have anything to do with DelayedArray. I'll file an issue under BiocParallel about this. 

Anyway, unless someone still runs into issues with `DelayedArray::rowSums()`, I'll close this in the next few days.

Cheers,
H.

```
> sessionInfo()
R version 3.6.0 Patched (2019-05-02 r76454)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS:   /home/hpages/R/R-3.6.r76454/lib/libRblas.so
LAPACK: /home/hpages/R/R-3.6.r76454/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] DelayedArray_0.11.8 BiocParallel_1.19.4 IRanges_2.19.17    
[4] S4Vectors_0.23.25   BiocGenerics_0.31.6 matrixStats_0.55.0 

loaded via a namespace (and not attached):
[1] compiler_3.6.0           Matrix_1.2-17            grid_3.6.0              
[4] DelayedMatrixStats_1.7.2 lattice_0.20-38         
```
